version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_container
    ports:
      - "80:80" # 映射 Nginx 端口
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
